# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20171119_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
