# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='presenter',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='event',
            name='presenter_position',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
